version: '3.9'

networks:
  internal_network:
    name: 'web3signer_hashicorp_plain_network'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: 'ws-vault-plain'
    command: server -config /config
    volumes:
      - "./data:/data"
      - "./config:/config"
    environment:
      - 'VAULT_SKIP_VERIFY=true'
      - 'VAULT_ENABLE_FILE_PERMISSIONS_CHECK=false'
    healthcheck:
      test: ["CMD-SHELL", "curl -k --fail http://localhost:8200/v1/sys/health?sealedcode=200&uninitcode=200"]
      interval: 3s
      retries: 3
    cap_add:
      - IPC_LOCK
    networks:
      - internal_network

  vault-agent:
    image: hashicorp/vault:latest
    container_name: 'ws-vault-agent-plain'
    command: agent -config /config
    ports:
      - "8200:8200"
    volumes:
      - "./vault-agent-config:/config"
      - ./creds:/creds
    environment:
      - 'VAULT_SKIP_VERIFY=true'
      - 'VAULT_ENABLE_FILE_PERMISSIONS_CHECK=false'
      - 'VAULT_ADDR=http://vault:8200'
    entrypoint: "vault agent -config /config/ -log-level debug"
    depends_on:
      init-vault:
        condition: service_completed_successfully
    networks:
      - internal_network
  
  init-vault:
    image: usmans/init-vault
    build:
      context: ./initvault
    container_name: "ws-vault-init"
    volumes:
      - ./creds:/creds
    depends_on:
      vault:
        condition: service_healthy
    command: http://vault:8200
    networks:
      - internal_network