http-listen-host: "0.0.0.0"
http-listen-port: 9000
http-host-allowlist: "*"

metrics-enabled: true
metrics-host: "0.0.0.0"
metrics-port: 9001
metrics-host-allowlist: "*"

logging: "INFO"

key-store-path: /var/config/keys

# eth2 subcommand options
# eth2.network: file:///var/config/e2e_config.yaml
eth2.slashing-protection-enabled: false
