version: "3.9"

networks:
  internal_network:
    name: '${INTERNAL_NETWORK_NAME}'

services:
  w3s-conf-gen:
    image: usmans/w3s-conf-gen:1.0.0
    container_name: 'w3s-conf-gen'
    command:
      - hashicorp
      - --token-file
      - /dummy.token
      - --count
      - ${KEYS_COUNT}
      - --output
      - /config/keys
      - --tls-knownhosts-file
      - /config/knownhosts
      - --url
      - http://vault-agent:8200/v1/secret
    volumes:
      - ./dummy.token:/dummy.token:ro
      - ../web3signer/config:/config
    networks:
      - internal_network
